version: '3'

services:

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/sites/nginx.conf:/etc/nginx/nginx.conf:ro
      #- ./nginx/conf.d/default.conf:/etc/nginx/default.conf:ro
      #- ./nginx/modsecurity.conf:/etc/nginx/modsecurity.conf:ro
      - ./myfrontend/build:/usr/share/nginx/html:ro
    depends_on:
      - backend

  backend:
    build:
      context: ./mybackend
    command: daphne -b 0.0.0.0 -p 8000 backend.asgi:application
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./mybackend:/code
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./myfrontend
    command: npm run build
    volumes:
      - ./myfrontend:/app
    depends_on:
      - backend

  redis:
    image: "redis:alpine"
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
    ports:
      - "6379:6379"
  
  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

volumes:
  grafana_data:
  prometheus_data:
