version: '3'

services:

  backend:
    build:
      context: ./mybackend
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
    volumes:
      - ./mybackend:/code
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./myfrontend
    command: npm start
    volumes:
      - ./myfrontend:/app
    ports:
      - "3000:3000"
