# Generated by Django 5.0.6 on 2024-06-15 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('open_orders', models.IntegerField(default=0)),
                ('total_orders', models.IntegerField(default=0)),
                ('observacoes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contractor')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline_date', models.DateTimeField()),
                ('delivery_status', models.BooleanField(default=False)),
                ('costs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('faturamento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contractor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contractor')),
            ],
        ),
    ]
