# Generated by Django 5.0.6 on 2024-06-17 14:00

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargasInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_status', models.CharField(choices=[('L', 'Liberada'), ('T', 'Em transito'), ('B', 'Bloqueada'), ('P', 'Pendente')], default='P', max_length=15)),
                ('type_of_load', models.CharField(max_length=100)),
                ('origin', django_countries.fields.CountryField(max_length=2)),
                ('destination', django_countries.fields.CountryField(max_length=2)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expected_delivery_date', models.DateTimeField()),
                ('contractorname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contractor')),
            ],
        ),
    ]
