# Generated by Django 5.0.6 on 2024-06-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cargasinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargasinfo',
            name='ce_mercante',
            field=models.CharField(default='', max_length=100),
        ),
    ]
