# Generated by Django 5.0.6 on 2024-06-17 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cargasinfo_ce_mercante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargasinfo',
            name='expected_delivery_date',
        ),
    ]
