# Generated by Django 5.0.6 on 2024-06-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_cargasinfo_expected_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargasinfo',
            name='contractorstring',
            field=models.CharField(default='', max_length=100),
        ),
    ]
