# Generated by Django 5.0.6 on 2024-06-21 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargasinfo',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='cargasinfo',
            name='origin',
        ),
    ]
