# Generated by Django 5.0.6 on 2024-06-21 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_cargasinfo_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargasinfo',
            name='origin',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.country'),
        ),
    ]
