# Generated by Django 5.0.6 on 2024-07-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_cargasinfo_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargasinfo',
            name='afrmmpago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cargasinfo',
            name='blnum',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='cargasinfo',
            name='cntrnum',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='cargasinfo',
            name='ncm',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='cargasinfo',
            name='nfnum',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='cargasinfo',
            name='referenciaid',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='cargasinfo',
            name='ce_mercante',
            field=models.CharField(default='', max_length=15),
        ),
    ]
