# Generated by Django 5.0.6 on 2024-07-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_cargasinfo_afrmmpago_cargasinfo_blnum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargasinfo',
            name='blfile',
            field=models.FileField(blank=True, null=True, upload_to='BL_arquivos/'),
        ),
    ]
