# Generated by Django 5.0.6 on 2024-07-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_cargasinfo_blfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargasinfo',
            name='afrmmfile',
            field=models.FileField(blank=True, null=True, upload_to='AFRMM_comprovantes'),
        ),
        migrations.AddField(
            model_name='cargasinfo',
            name='ce_m_file',
            field=models.FileField(blank=True, null=True, upload_to='CE_MERCANTE_arquivos'),
        ),
        migrations.AddField(
            model_name='cargasinfo',
            name='packinglist',
            field=models.FileField(blank=True, null=True, upload_to='PACKING_LIST_arquivos'),
        ),
    ]
