# Generated by Django 5.0.6 on 2024-07-19 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_cargasinfo_afrmmfile_cargasinfo_ce_m_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('cnpj', models.CharField(max_length=14)),
                ('faturamento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lucro', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='cargasinfo',
            name='blfile',
            field=models.FileField(blank=True, null=True, upload_to='BL_arquivos'),
        ),
        migrations.AddField(
            model_name='cargasinfo',
            name='companyid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.company'),
        ),
    ]
