# Generated by Django 5.0.6 on 2024-07-21 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_company_alter_cargasinfo_blfile_cargasinfo_companyid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_operador', models.CharField(max_length=100)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(max_length=100)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cargasinfo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contractor')),
            ],
        ),
    ]
